[workspace.package]
edition = "2024"
authors = ["Teshin <1443965173@qq.com>"]
description = "Agent engine for free-agent system"
repository = "https://github.com/woshihaoren4/free-agent-engine"
license = "Apache-2.0"
readme = "README.md"

[workspace]
resolver = "3"
members = [
    "app/fae",
    "crates/fae-agent",
    "crates/fae-engine",
    "examples",
    "crates/async-openai",
]

[workspace.dependencies]
wd_log = "0.4.0"
wd_tools = { version = "0.14.10", features = ["b64", "md5", "point-free", "hex", "ptr", "snowflake","uid","time","sync","fs","pool","chan","coll","ctx","mutex","regex_simple","global","random"],registry = "crates-io" }
wd_event = {version = "0.8.4",registry = "crates-io"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.50", features = ["full"] }
anyhow = "1.0.102"
thiserror = "2.0.18"
async-trait = "0.1.89"
tokio-stream = "0.1.17"
serde_yaml = "0.9.34"
