[package]
name = "fae-ctl"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
wd_log = "0.4.0"
wd_tools = "0.14.10"
clap = {version =  "4.5.50",features = ["derive"] }
