[package]
name = "fae"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
wd_log = "0.4.0"
wd_tools = "0.14.10"
clap = {version =  "4.5.50",features = ["derive"] }
fae-agent = { version = "0.1.0", path = "../../crates/fae-agent" }
fae-engine = { version = "0.1.0", path = "../../crates/fae-engine" }
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
dirs = "6.0.0"
crossterm = "0.29.0"
tui-input = "0.15.3"
unicode-width = "0.2.2"
reqwest = "0.13.3"
zip = "8.6.0"
anyhow = "1.0.102"
